### PR TITLE
A bunch of additional hooks [rebase]

### PR DESCRIPTION
**Pull request by patcon**
Just a rebase of @geekgonecrazy's branch.

cc: @n0mer

### CODE REVIEW

**Comment by patcon** [comment]
I just realized that this shouldn't be merged until we have something in place for https://github.com/hubot-scripts/hubot-github-repo-event-notifier/issues/9

As it stands, this would make issues and pull request hooks much more noisy, with no way of dialing it back.

If anyone wants to implement that, then I'd be happy to merge. Feel free to point out if I've misunderstood something going on here (not using it myself right now) :)

**Comment by geekgonecrazy** [comment]
So you want to be able to filter the event action types on top of just event types?

**Comment by patcon** [comment]
I think before merging, that would be reasonable. (?) If anyone is using this with a decently-active repo, notifying on every issue action would be lots of noise -- I know it would have effectively broken our use-case when we were using it in #gittip

Sorry if it seems overly cautious. If it's not useful to you, I'm sure someone will take it up later -- maybe me :)

**Comment by geekgonecrazy** [comment]
Looks like it was started here: https://github.com/martinb3/hubot-github-repo-event-notifier/commit/132deb90a4c3c5876ddc70e2deb6ddb9304f8700  

So won't need to be too creative.  :)  I can do this.  Just going to have to do some reverting on my fork and apply these changes.

**Comment by geekgonecrazy** [comment]
#27 hopefully will resolve this prereq.

**Comment by leefaus** [comment]
@patcon @geekgonecrazy 

I'm :+1: for this change.  Tested locally and working great.

**Comment by patcon** [comment]
:+1: :100: 

thanks! Glad the main chunk of changes got in :)

**Comment by patcon** [comment]
Released in v1.5.0

**Comment by geekgonecrazy** [comment]
awesome!  :)  Want me to put in a PR to bump the version so npm picks things up?

**Comment by geekgonecrazy** [comment]
nvm :+1:

**Pull request merged**
