### PR TITLE
Fixed javascript syntax mixed in with coffeescript. Also updated readme

### PR DESCRIPTION
**Pull request by geekgonecrazy**
Attn: @patcon in reference to #29 

This fixes the issue that was introduced.  Also added usage examples to the readme.

### CODE REVIEW

**Comment by patcon** [comment]
You are awesome. Thanks! I'll fix up the whitespace later and re-release

(If I could be so bold as to suggest, you should maybe consider configuring your IDE to not be so heavy-handed in changing whitespace every time you contribute :)

**Comment by geekgonecrazy** [comment]
@patcon man!  I'm not sure why it does that.  I'm using atom, and the [editorconfig](https://atom.io/packages/editorconfig) package.  It always acts like its honoring it.  But in this repo it seems to tear it up..

Suggestions? I'd for sure like to make less work on you.

**Comment by geekgonecrazy** [comment]
Also hold on this.  Heh Just spotted something.  Will also try and fix this white space

**Comment by patcon** [comment]
Ah rats. Didn't see that in time. Sorry man!

**Comment by patcon** [comment]
I'll hold off on releasing till I hear back on that other thing. And thanks for your consideration -- added an editorconfig and hopefully that'll help out the atom folks

**Pull request merged**
