### PR TITLE
adding a handler for push events

### PR DESCRIPTION
**Pull request by csanner**

### CODE REVIEW

**Comment by secrettriangle** [comment]
Can we get this merged already?

**Comment by parkr** [comment]
It requires a small documentation change in the top of the file.

**Comment by n0mer** [comment]
@parkr is this "small documentation change" ready yet?

**Comment by patcon** [comment]
heh. now released in v1.4.0 :)
https://www.npmjs.com/package/hubot-github-repo-event-notifier

**Comment by n0mer** [comment]
:+1:

**Comment by n0mer** [comment]
@patcon what about https://github.com/hubot-scripts/hubot-github-repo-event-notifier/pull/20 ?

**Comment by patcon** [comment]
Would you be able to fetch that branch and add fixtures in `test/fixtures` (just copy them from the API pages) and add to the script tomdocs the new eventTypes?

**Comment by n0mer** [comment]
@patcon sorry, are you asking me to do this?

**Comment by patcon** [comment]
heh, yep, if you're itching to see it merged. Yay open source participation! :)

(you can always use this: https://docs.npmjs.com/files/package.json#git-urls-as-dependencies)

**Comment by patcon** [comment]
On further consideration, (re: #26), I think #20 is more than just doc changes, and should be split up if folks would like to see it merged.

Of course, if I start using this script again, I'll probably do it myself, but until then, I'll leave it in someone else's court

**Comment by n0mer** [comment]
@patcon unfortunately i'm not js dev.

I can contribute by running changes published to dedicated branch on my server, to see whether new features or fixes work or not.

**Comment by patcon** [comment]
Ah, gotcha. thanks @n0mer :)

**Pull request merged**
